"""initial structured infrastructure domain

Revision ID: 5959e77dbc77
Revises: 
Create Date: 2026-08-19 01:59:32.309812
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '5959e77dbc77'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizations',
    sa.Column('name', sa.String(length=180), nullable=False),
    sa.Column('organization_type', sa.Enum('CUSTOMER', 'CONTRACTOR', 'PARTNER', 'INTERNAL', name='organizationtype', native_enum=False), nullable=False),
    sa.Column('external_reference', sa.String(length=180), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('organizations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_organizations_name'), ['name'], unique=False)

    op.create_table('standard_profiles',
    sa.Column('tenant_id', sa.Uuid(), nullable=True),
    sa.Column('name', sa.String(length=180), nullable=False),
    sa.Column('standard_family', sa.String(length=50), nullable=False),
    sa.Column('edition', sa.String(length=20), nullable=False),
    sa.Column('effective_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('rules_json', sa.JSON(), nullable=False),
    sa.Column('identifier_templates', sa.JSON(), nullable=False),
    sa.Column('validation_rules', sa.JSON(), nullable=False),
    sa.Column('label_templates', sa.JSON(), nullable=False),
    sa.Column('required_records', sa.JSON(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'standard_family', 'edition', 'name', name='uq_standard_profile_scope')
    )
    with op.batch_alter_table('standard_profiles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_standard_profiles_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('tenants',
    sa.Column('owner_organization_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=180), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('compliance_mode', sa.String(length=20), nullable=False),
    sa.Column('active_standard_profile_id', sa.Uuid(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['active_standard_profile_id'], ['standard_profiles.id'], ),
    sa.ForeignKeyConstraint(['owner_organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug', name='uq_tenant_slug')
    )
    op.create_table('user_identities',
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('display_name', sa.String(length=180), nullable=False),
    sa.Column('oidc_subject', sa.String(length=255), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email', name='uq_user_identity_email'),
    sa.UniqueConstraint('oidc_subject')
    )
    with op.batch_alter_table('user_identities', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_identities_organization_id'), ['organization_id'], unique=False)

    with op.batch_alter_table('standard_profiles', schema=None) as batch_op:
        batch_op.create_foreign_key(
            'fk_standard_profiles_tenant_id_tenants',
            'tenants',
            ['tenant_id'],
            ['id'],
            ondelete='CASCADE',
        )

    op.create_table('audit_events',
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('actor_id', sa.Uuid(), nullable=False),
    sa.Column('actor_organization_id', sa.Uuid(), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('object_type', sa.String(length=80), nullable=False),
    sa.Column('object_id', sa.Uuid(), nullable=False),
    sa.Column('before', sa.JSON(), nullable=True),
    sa.Column('after', sa.JSON(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('request_id', sa.String(length=100), nullable=True),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_events_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_events_request_id'), ['request_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_events_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index('ix_audit_object', ['tenant_id', 'object_type', 'object_id'], unique=False)
        batch_op.create_index('ix_audit_tenant_time', ['tenant_id', 'timestamp'], unique=False)

    op.create_table('device_templates',
    sa.Column('manufacturer', sa.String(length=120), nullable=False),
    sa.Column('model', sa.String(length=120), nullable=False),
    sa.Column('device_type', sa.String(length=80), nullable=False),
    sa.Column('rack_units', sa.Integer(), nullable=False),
    sa.Column('width_mm', sa.Integer(), nullable=False),
    sa.Column('depth_mm', sa.Integer(), nullable=False),
    sa.Column('height_mm', sa.Integer(), nullable=True),
    sa.Column('port_blueprint', sa.JSON(), nullable=False),
    sa.Column('model_3d_reference', sa.String(length=500), nullable=True),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'manufacturer', 'model', name='uq_device_template_model')
    )
    with op.batch_alter_table('device_templates', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_device_templates_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('labels',
    sa.Column('standard_profile_id', sa.Uuid(), nullable=False),
    sa.Column('object_type', sa.String(length=50), nullable=False),
    sa.Column('object_id', sa.Uuid(), nullable=False),
    sa.Column('identifier', sa.String(length=180), nullable=False),
    sa.Column('template_name', sa.String(length=120), nullable=False),
    sa.Column('qr_payload', sa.String(length=1000), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['standard_profile_id'], ['standard_profiles.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('labels', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_labels_object_id'), ['object_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_labels_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('locations',
    sa.Column('parent_id', sa.Uuid(), nullable=True),
    sa.Column('location_type', sa.Enum('REGION', 'CAMPUS', 'SITE', 'BUILDING', 'FLOOR', 'ZONE', 'ROOM', 'TR', 'ER', 'MDF', 'MMR', 'DATA_HALL', 'ENTRANCE_FACILITY', 'ROW', 'OTHER', name='locationtype', native_enum=False), nullable=False),
    sa.Column('identifier', sa.String(length=180), nullable=False),
    sa.Column('name', sa.String(length=180), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('coordinates', sa.JSON(), nullable=False),
    sa.Column('dimensions', sa.JSON(), nullable=False),
    sa.Column('transform_3d', sa.JSON(), nullable=False),
    sa.Column('floor_plan_reference', sa.String(length=500), nullable=True),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['locations.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'identifier', name='uq_location_identifier_tenant')
    )
    with op.batch_alter_table('locations', schema=None) as batch_op:
        batch_op.create_index('ix_location_tenant_parent', ['tenant_id', 'parent_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_locations_parent_id'), ['parent_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_locations_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('projects',
    sa.Column('project_number', sa.String(length=80), nullable=False),
    sa.Column('name', sa.String(length=180), nullable=False),
    sa.Column('customer_organization_id', sa.Uuid(), nullable=False),
    sa.Column('contractor_organization_id', sa.Uuid(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('planned_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('planned_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('actual_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('actual_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['contractor_organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['customer_organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'project_number', name='uq_project_number_tenant')
    )
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_projects_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('tenant_memberships',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('role', sa.String(length=80), nullable=False),
    sa.Column('permissions', sa.JSON(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user_identities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'user_id', name='uq_tenant_membership_user')
    )
    with op.batch_alter_table('tenant_memberships', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tenant_memberships_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('access_grants',
    sa.Column('subject_organization_id', sa.Uuid(), nullable=False),
    sa.Column('subject_user_id', sa.Uuid(), nullable=True),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('location_id', sa.Uuid(), nullable=True),
    sa.Column('permissions', sa.JSON(), nullable=False),
    sa.Column('approved_by', sa.Uuid(), nullable=False),
    sa.Column('starts_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'ACTIVE', 'REVOKED', 'EXPIRED', name='accessgrantstatus', native_enum=False), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_by', sa.Uuid(), nullable=True),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['approved_by'], ['user_identities.id'], ),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subject_organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['subject_user_id'], ['user_identities.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('access_grants', schema=None) as batch_op:
        batch_op.create_index('ix_access_grant_subject', ['tenant_id', 'subject_user_id', 'status'], unique=False)
        batch_op.create_index(batch_op.f('ix_access_grants_expires_at'), ['expires_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_access_grants_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('cables',
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.Column('identifier', sa.String(length=180), nullable=False),
    sa.Column('media_type', sa.String(length=80), nullable=False),
    sa.Column('construction', sa.String(length=80), nullable=False),
    sa.Column('manufacturer', sa.String(length=120), nullable=True),
    sa.Column('part_number', sa.String(length=120), nullable=True),
    sa.Column('color', sa.String(length=50), nullable=True),
    sa.Column('length_m', sa.Float(), nullable=True),
    sa.Column('measured_length_m', sa.Float(), nullable=True),
    sa.Column('strand_count', sa.Integer(), nullable=True),
    sa.Column('pair_count', sa.Integer(), nullable=True),
    sa.Column('installation_status', sa.Enum('PLANNED', 'APPROVED', 'ORDERED', 'STAGED', 'INSTALLED', 'TERMINATED', 'TESTED', 'COMMISSIONED', 'IN_SERVICE', 'SPARE', 'ABANDONED', 'REMOVED', name='cablestatus', native_enum=False), nullable=False),
    sa.Column('installer_id', sa.Uuid(), nullable=True),
    sa.Column('installed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('tested_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('test_status', sa.String(length=30), nullable=True),
    sa.Column('owner_organization_id', sa.Uuid(), nullable=True),
    sa.Column('maintenance_owner_id', sa.Uuid(), nullable=True),
    sa.Column('custom_attributes', sa.JSON(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'identifier', name='uq_cable_identifier_tenant')
    )
    with op.batch_alter_table('cables', schema=None) as batch_op:
        batch_op.create_index('ix_cable_tenant_status', ['tenant_id', 'installation_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_cables_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_cables_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('pathways',
    sa.Column('location_id', sa.Uuid(), nullable=False),
    sa.Column('identifier', sa.String(length=180), nullable=False),
    sa.Column('name', sa.String(length=180), nullable=False),
    sa.Column('pathway_type', sa.String(length=80), nullable=False),
    sa.Column('capacity_area_mm2', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'identifier', name='uq_pathway_identifier_tenant')
    )
    with op.batch_alter_table('pathways', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pathways_location_id'), ['location_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_pathways_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('racks',
    sa.Column('location_id', sa.Uuid(), nullable=False),
    sa.Column('rack_identifier', sa.String(length=180), nullable=False),
    sa.Column('name', sa.String(length=180), nullable=False),
    sa.Column('role', sa.String(length=80), nullable=True),
    sa.Column('manufacturer', sa.String(length=120), nullable=True),
    sa.Column('model', sa.String(length=120), nullable=True),
    sa.Column('height_u', sa.Integer(), nullable=False),
    sa.Column('width_mm', sa.Integer(), nullable=False),
    sa.Column('depth_mm', sa.Integer(), nullable=False),
    sa.Column('max_weight_kg', sa.Float(), nullable=True),
    sa.Column('position_x', sa.Float(), nullable=False),
    sa.Column('position_y', sa.Float(), nullable=False),
    sa.Column('position_z', sa.Float(), nullable=False),
    sa.Column('rotation', sa.Float(), nullable=False),
    sa.Column('front_direction', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('reserved_units', sa.JSON(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('height_u >= 1 AND height_u <= 60', name='ck_rack_height'),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'rack_identifier', name='uq_rack_identifier_tenant')
    )
    with op.batch_alter_table('racks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_racks_location_id'), ['location_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_racks_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('devices',
    sa.Column('rack_id', sa.Uuid(), nullable=True),
    sa.Column('location_id', sa.Uuid(), nullable=False),
    sa.Column('template_id', sa.Uuid(), nullable=True),
    sa.Column('identifier', sa.String(length=180), nullable=False),
    sa.Column('name', sa.String(length=180), nullable=False),
    sa.Column('device_type', sa.String(length=80), nullable=False),
    sa.Column('rack_units', sa.Integer(), nullable=False),
    sa.Column('start_u', sa.Integer(), nullable=False),
    sa.Column('face', sa.String(length=20), nullable=False),
    sa.Column('serial_number', sa.String(length=180), nullable=True),
    sa.Column('asset_tag', sa.String(length=180), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('instance_overrides', sa.JSON(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['rack_id'], ['racks.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['template_id'], ['device_templates.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'identifier', name='uq_device_identifier_tenant')
    )
    with op.batch_alter_table('devices', schema=None) as batch_op:
        batch_op.create_index('ix_device_rack_u', ['tenant_id', 'rack_id', 'start_u', 'face'], unique=False)
        batch_op.create_index(batch_op.f('ix_devices_asset_tag'), ['asset_tag'], unique=False)
        batch_op.create_index(batch_op.f('ix_devices_location_id'), ['location_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_devices_rack_id'), ['rack_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_devices_serial_number'), ['serial_number'], unique=False)
        batch_op.create_index(batch_op.f('ix_devices_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('pathway_segments',
    sa.Column('pathway_id', sa.Uuid(), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=180), nullable=False),
    sa.Column('length_m', sa.Float(), nullable=False),
    sa.Column('capacity_area_mm2', sa.Float(), nullable=True),
    sa.Column('reserved_percent', sa.Float(), nullable=False),
    sa.Column('coordinates', sa.JSON(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['pathway_id'], ['pathways.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'pathway_id', 'sequence', name='uq_pathway_segment_sequence')
    )
    with op.batch_alter_table('pathway_segments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pathway_segments_pathway_id'), ['pathway_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_pathway_segments_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('work_orders',
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('location_id', sa.Uuid(), nullable=True),
    sa.Column('cable_id', sa.Uuid(), nullable=True),
    sa.Column('work_order_number', sa.String(length=80), nullable=False),
    sa.Column('title', sa.String(length=180), nullable=False),
    sa.Column('description', sa.String(length=2000), nullable=False),
    sa.Column('assigned_organization_id', sa.Uuid(), nullable=False),
    sa.Column('assigned_user_id', sa.Uuid(), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'READY', 'IN_PROGRESS', 'AWAITING_TEST', 'AWAITING_APPROVAL', 'COMPLETED', 'CANCELLED', name='workorderstatus', native_enum=False), nullable=False),
    sa.Column('due_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['assigned_organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['assigned_user_id'], ['user_identities.id'], ),
    sa.ForeignKeyConstraint(['cable_id'], ['cables.id'], ),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'work_order_number', name='uq_work_order_number_tenant')
    )
    with op.batch_alter_table('work_orders', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_work_orders_cable_id'), ['cable_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_work_orders_location_id'), ['location_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_work_orders_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_work_orders_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('cable_route_segments',
    sa.Column('cable_id', sa.Uuid(), nullable=False),
    sa.Column('pathway_segment_id', sa.Uuid(), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['cable_id'], ['cables.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['pathway_segment_id'], ['pathway_segments.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'cable_id', 'sequence', name='uq_cable_route_sequence')
    )
    with op.batch_alter_table('cable_route_segments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cable_route_segments_cable_id'), ['cable_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_cable_route_segments_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('ports',
    sa.Column('device_id', sa.Uuid(), nullable=False),
    sa.Column('identifier', sa.String(length=100), nullable=False),
    sa.Column('label', sa.String(length=180), nullable=False),
    sa.Column('connector_type', sa.String(length=80), nullable=False),
    sa.Column('media_type', sa.String(length=80), nullable=False),
    sa.Column('direction', sa.String(length=30), nullable=False),
    sa.Column('front_or_rear', sa.String(length=20), nullable=False),
    sa.Column('position_index', sa.Integer(), nullable=False),
    sa.Column('position', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('termination_type', sa.String(length=80), nullable=True),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'device_id', 'identifier', name='uq_port_device_identifier')
    )
    with op.batch_alter_table('ports', schema=None) as batch_op:
        batch_op.create_index('ix_port_tenant_device_position', ['tenant_id', 'device_id', 'position_index'], unique=False)
        batch_op.create_index(batch_op.f('ix_ports_device_id'), ['device_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ports_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('test_records',
    sa.Column('cable_id', sa.Uuid(), nullable=False),
    sa.Column('work_order_id', sa.Uuid(), nullable=True),
    sa.Column('tester_id', sa.Uuid(), nullable=False),
    sa.Column('result', sa.String(length=20), nullable=False),
    sa.Column('measurements', sa.JSON(), nullable=False),
    sa.Column('tested_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('attachment_name', sa.String(length=500), nullable=True),
    sa.Column('attachment_object_key', sa.String(length=500), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('approved_by', sa.Uuid(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['cable_id'], ['cables.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['work_order_id'], ['work_orders.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('test_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_test_records_cable_id'), ['cable_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_test_records_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('cable_terminations',
    sa.Column('cable_id', sa.Uuid(), nullable=False),
    sa.Column('side', sa.String(length=1), nullable=False),
    sa.Column('port_id', sa.Uuid(), nullable=False),
    sa.Column('strand', sa.Integer(), nullable=True),
    sa.Column('pair', sa.Integer(), nullable=True),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("side IN ('A', 'B')", name='ck_cable_termination_side'),
    sa.ForeignKeyConstraint(['cable_id'], ['cables.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['port_id'], ['ports.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'cable_id', 'side', name='uq_cable_side'),
    sa.UniqueConstraint('tenant_id', 'port_id', name='uq_physical_port_termination')
    )
    with op.batch_alter_table('cable_terminations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cable_terminations_cable_id'), ['cable_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_cable_terminations_port_id'), ['port_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_cable_terminations_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('port_mappings',
    sa.Column('source_port_id', sa.Uuid(), nullable=False),
    sa.Column('target_port_id', sa.Uuid(), nullable=False),
    sa.Column('mapping_type', sa.String(length=50), nullable=False),
    sa.Column('lane', sa.Integer(), nullable=True),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('source_port_id <> target_port_id', name='ck_port_mapping_not_self'),
    sa.ForeignKeyConstraint(['source_port_id'], ['ports.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_port_id'], ['ports.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'source_port_id', 'target_port_id', name='uq_port_mapping')
    )
    with op.batch_alter_table('port_mappings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_port_mappings_source_port_id'), ['source_port_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_port_mappings_target_port_id'), ['target_port_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_port_mappings_tenant_id'), ['tenant_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('port_mappings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_port_mappings_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_port_mappings_target_port_id'))
        batch_op.drop_index(batch_op.f('ix_port_mappings_source_port_id'))

    op.drop_table('port_mappings')
    with op.batch_alter_table('cable_terminations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cable_terminations_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_cable_terminations_port_id'))
        batch_op.drop_index(batch_op.f('ix_cable_terminations_cable_id'))

    op.drop_table('cable_terminations')
    with op.batch_alter_table('test_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_test_records_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_test_records_cable_id'))

    op.drop_table('test_records')
    with op.batch_alter_table('ports', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ports_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_ports_device_id'))
        batch_op.drop_index('ix_port_tenant_device_position')

    op.drop_table('ports')
    with op.batch_alter_table('cable_route_segments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cable_route_segments_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_cable_route_segments_cable_id'))

    op.drop_table('cable_route_segments')
    with op.batch_alter_table('work_orders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_work_orders_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_work_orders_project_id'))
        batch_op.drop_index(batch_op.f('ix_work_orders_location_id'))
        batch_op.drop_index(batch_op.f('ix_work_orders_cable_id'))

    op.drop_table('work_orders')
    with op.batch_alter_table('pathway_segments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pathway_segments_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_pathway_segments_pathway_id'))

    op.drop_table('pathway_segments')
    with op.batch_alter_table('devices', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_devices_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_devices_serial_number'))
        batch_op.drop_index(batch_op.f('ix_devices_rack_id'))
        batch_op.drop_index(batch_op.f('ix_devices_location_id'))
        batch_op.drop_index(batch_op.f('ix_devices_asset_tag'))
        batch_op.drop_index('ix_device_rack_u')

    op.drop_table('devices')
    with op.batch_alter_table('racks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_racks_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_racks_location_id'))

    op.drop_table('racks')
    with op.batch_alter_table('pathways', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pathways_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_pathways_location_id'))

    op.drop_table('pathways')
    with op.batch_alter_table('cables', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cables_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_cables_project_id'))
        batch_op.drop_index('ix_cable_tenant_status')

    op.drop_table('cables')
    with op.batch_alter_table('access_grants', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_access_grants_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_access_grants_expires_at'))
        batch_op.drop_index('ix_access_grant_subject')

    op.drop_table('access_grants')
    with op.batch_alter_table('tenant_memberships', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tenant_memberships_tenant_id'))

    op.drop_table('tenant_memberships')
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_projects_tenant_id'))

    op.drop_table('projects')
    with op.batch_alter_table('locations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_locations_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_locations_parent_id'))
        batch_op.drop_index('ix_location_tenant_parent')

    op.drop_table('locations')
    with op.batch_alter_table('labels', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_labels_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_labels_object_id'))

    op.drop_table('labels')
    with op.batch_alter_table('device_templates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_device_templates_tenant_id'))

    op.drop_table('device_templates')
    with op.batch_alter_table('audit_events', schema=None) as batch_op:
        batch_op.drop_index('ix_audit_tenant_time')
        batch_op.drop_index('ix_audit_object')
        batch_op.drop_index(batch_op.f('ix_audit_events_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_audit_events_request_id'))
        batch_op.drop_index(batch_op.f('ix_audit_events_project_id'))

    op.drop_table('audit_events')
    with op.batch_alter_table('user_identities', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_identities_organization_id'))

    op.drop_table('user_identities')
    with op.batch_alter_table('standard_profiles', schema=None) as batch_op:
        batch_op.drop_constraint('fk_standard_profiles_tenant_id_tenants', type_='foreignkey')

    op.drop_table('tenants')
    with op.batch_alter_table('standard_profiles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_standard_profiles_tenant_id'))

    op.drop_table('standard_profiles')
    with op.batch_alter_table('organizations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_organizations_name'))

    op.drop_table('organizations')
    # ### end Alembic commands ###
